source "https://rubygems.org"

ruby "3.1.3"

gem "debug", "~> 1.7"
gem "dotenv"
gem "honeybadger", "~> 5.2"
gem "json"
gem "platform-api"
gem "rake"
gem "sidekiq", "< 7"
gem "sinatra"
gem "faraday"
gem "standard", "~> 1.22"
gem "httparty", "~> 0.21.0"
