source "https://rubygems.org"

ruby "3.1.3"

gem "debug", "~> 1.11"
gem "dotenv"
gem "honeybadger", "~> 6.5"
gem "json"
gem "platform-api"
gem "rake"
gem "sidekiq", "< 8"
gem "sinatra"
gem "faraday"
gem "standard", "~> 1.54"
gem "httparty", "~> 0.24.2"
